@startuml
actor ":Bibliotecario"
":Bibliotecario" -> ":Main" : iniciarAplicacion()
":Main" -> ":VentanaPrincipal" : inicializarVentana()
":VentanaPrincipal" -> ":VentanaPrincipal" : configurarBoton()
":VentanaPrincipal" -> ":VentanaPrincipal" : cargarIconos()
":VentanaPrincipal" -> ":VentanaPrincipal" : inicializarGestores()
":VentanaRegistrarLibro" -> ":VentanaPrincipal" : configurarInteraccion()
":VentanaPrincipal" -> ":VentanaRegistrarLibro" : inicializarVentana()
":VentanaPrincipal" -> ":VentanaRegistrarLibro" : configurarInteraccion()

":VentanaRegistrarLibro" -> ":Libro" : ingresarDatosDelLibro()
":Libro" -> ":VentanaRegistrarLibro" : configurarInteraccion()
":Inventario" -> ":Libro" : obtenerDatosDelLibro()
":Libro" -> ":GestorDeLibro" : editarInformacionDelLibro()
":GestorDeLibro" -> ":VentanaRegistrarLibro" : configurarInteraccion()
":Inventario" <- ":Libro" : agregarLibro()
":Inventario" <- ":Libro" : obtenerDatosDelInventario()
":Inventario" -> ":GestorDeInventario" : actualizarInventario()
":GestorDeInventario" -> ":VentanaRegistrarLibro" : configurarInteraccion()

@enduml
